// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace WarriorGameplayTags
{
	/** Input Tags **/
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	
	/** Player Tags **/
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe)
	UNREALCOMBATMECHANICS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe)
}